name: Deploy to Test VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Test VM via SSH
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          sshpass -p "$REMOTE_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            set -e
            cd /home/budget_app  # Replace this with your actual project directory on the VM
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
